
networks:
  app-tier:
    driver: bridge


services:
  app:
    image: mmdl-v0.7.1
    ports:
      - 3000:3000
    volumes:
      - ./:/app/data # Mounts a local 'data' directory to the container's '/app/data'
    networks:
      - app-tier   
    restart: always
    env_file:
      - .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
