import { getAllCalDavAccountsFromDexie, getCalDAVSummaryFromDexie } from "@/helpers/frontend/dexie/caldav_dexie";
import { getAllCalendarsFromCalDavAccountIDFromDexie, updateCalendarColourbyID_Dexie } from "@/helpers/frontend/dexie/calendars_dexie";
import { getI18nObject } from "@/helpers/frontend/general";
import { getAuthenticationHeadersforUser } from "@/helpers/frontend/user";
import { getAPIURL } from "@/helpers/general";
import { useEffect, useState } from "react";
import { Button, Col, Modal, Row } from "react-bootstrap";
import { AiOutlineDelete, AiOutlinePlusCircle } from "react-icons/ai";
import { toast } from "react-toastify";
import ColourPicker from "../../ColourPIcker";
import { isDarkModeEnabled } from "@/helpers/frontend/theme";

interface functionalProps {

    calendarAddButtonClicked: Function;
    caldavAccountDeleteClicked: Function;
    context: any;
    makeDeleteRequest: Function;
}

// Generated by https://quicktype.io

export interface CaldavAccount {
    name:               string;
    username:           string;
    url:                string;
    caldav_accounts_id: number;
    id:                 number;
    calendars:          Calendar[];
}

export interface Calendar {
    caldav_accounts_id: number;
    displayName:        string;
    url:                string;
    ctag:               string;
    description:        string;
    calendarColor:      string;
    syncToken:          string;
    timezone:           string;
    resourcetype:       Resourcetype;
    calendars_id:       number;
}

export enum Resourcetype {
    CollectionCalendar = "collection,calendar",
}

export const CaldavAccountTable = (props: functionalProps) => {
    const i18next = getI18nObject()
    const [caldavAccounts, setCalDAVAccounts] = useState<CaldavAccount[]>([])
    const [showDeleteAccountModal, setShowDeleteAccountModal] = useState(false)
    const [calendartoDelete, setCalendartoDelete] = useState<CaldavAccount | null>(null)
    const [updated, setUpdatedVal] = useState(Date.now())

    var output: JSX.Element []= [];
    useEffect(() => {
        getCalDAVSummaryFromDexie().then(response => {
            setCalDAVAccounts(response)
        })
    }, [updated])

    function makeDeleteRequest(calToDelete) {
        setShowDeleteAccountModal(false)
        props.makeDeleteRequest(calToDelete)
    }
    function getDeleteModal() {
        if(!calendartoDelete)
        {
            return 
        }
        // console.log("calendartoDelete", calendartoDelete)
        if(!("name" in calendartoDelete)){
            return
        }
        var body = (
            <>
                <p>{i18next.t("DELETE_CALDAV_ACCOUNT_CONFIRMATION")}</p>
                <h3>{calendartoDelete.name}</h3>
            </>
        )
        return (
            <>
                <Modal centered show={showDeleteAccountModal} onHide={() => setShowDeleteAccountModal(false)}>
                    <Modal.Header closeButton>
                    </Modal.Header>
                    <Modal.Body>{body}</Modal.Body>
                    <Modal.Footer>
                        <Button variant="secondary" onClick={() => setShowDeleteAccountModal(false)}>
                            {i18next.t("BACK")}
                        </Button>
                        <Button variant="danger" onClick={() => makeDeleteRequest(calendartoDelete.caldav_accounts_id)}>
                            {i18next.t("DELETE")}
                        </Button>
                    </Modal.Footer>
                </Modal>

            </>
        )


    }

    function caldavAccountDeleteClicked(caldavAccount) {
        setCalendartoDelete(caldavAccount)
        setShowDeleteAccountModal(true)
    }

    function calendarColourChanged(newColour, keyName) {
        console.log(newColour, keyName)
        if (newColour && keyName) {
            //Make update Calendar Colour Request.
            updateCalendarColourbyID_Dexie(keyName, newColour).then(resultofUpdate => {
                toast.success(i18next.t("UPDATE_OK"))
                setUpdatedVal(Date.now())
            })
        }
    }
    if (caldavAccounts && Array.isArray(caldavAccounts) && caldavAccounts.length > 0) {

        for (const i in caldavAccounts) {
            let temp_cal : JSX.Element[] = []
            let calendars = caldavAccounts[i]["calendars"]
            for (const j in calendars) {
                var border = "3px solid " + calendars[j].calendarColor
                var cal = (
                    <Row key={calendars[j].displayName} xs={5} style={{ border: border, borderRadius: 10, margin: 5, padding: 5 }}>
                        <Col>
                            <h5 className="textDefault">{calendars[j].displayName}</h5>
                        </Col>
                        <Col className="d-flex justify-content-center">
                            <ColourPicker onChange={calendarColourChanged} colour={calendars[j].calendarColor} keyName={calendars[j].calendars_id.toString()} />
                        </Col>

                    </Row>
                )
                temp_cal.push(cal)
            }

            //                console.log("allCals", allCals)

            const backgroundColor = isDarkModeEnabled() ? "black": "#f5f5f5"
            const borderColor = isDarkModeEnabled() ? "white" : "#f5f5f5"
            output.push
                (
                    <div key={"cal_" + caldavAccounts[i].name} style={{ border:`1px solid ${borderColor}`, background: backgroundColor,  borderRadius: 10, padding: 20, margin: 10, marginBottom: 30 }}>
                        <Row>
                            <Col>
                                <h1>{caldavAccounts[i].name}</h1>
                            </Col>
                            <Col onClick={() => caldavAccountDeleteClicked(caldavAccounts[i])} style={{ textAlign: "right", color: "red" }}><AiOutlineDelete /></Col>
                        </Row>
                        <p>{
                            caldavAccounts[i].url
                        }</p>
                        <h2>{i18next.t("CALENDARS")} <AiOutlinePlusCircle onClick={() => props.calendarAddButtonClicked(caldavAccounts[i])} /></h2>
                        <Row>{temp_cal}
                        </Row>


                    </div>
                )

        }


    }



    if (output.length == 0) {
        return i18next.t("NOTHING_TO_SHOW")
    }
    return (
        <>
            {output}
            {showDeleteAccountModal ? getDeleteModal() : null}
        </>
    )
}

